export const products = [
  {
    id: 1,
    name: "Classic Sofa",
    cost: 1000,
    category: "sofa",
    colors: ["red", "blue", "green"],
    size: ["S", "M", "L"],
    tags: ["vintage", "leather", "classic"],
    rating: 4,
    description: "A classic leather sofa, perfect for any living room.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 2,
    name: "Modern Chair",
    cost: 300,
    category: "chair",
    colors: ["black", "white"],
    size: ["S", "M"],
    tags: ["modern", "minimalistic"],
    rating: 4.5,
    description: "A modern chair with a minimalistic design.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 3,
    name: "Dining Table",
    cost: 750,
    category: "table",
    colors: ["brown"],
    size: ["M", "L"],
    tags: ["wooden", "dining"],
    rating: 5,
    description: "A sturdy wooden dining table.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 4,
    name: "Queen Bed",
    cost: 1500,
    category: "bed",
    colors: ["white", "grey"],
    size: ["M", "L"],
    tags: ["queen-size", "comfortable"],
    rating: 4.7,
    description: "A queen-sized bed for ultimate relaxation.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 5,
    name: "Luxury Sofa",
    cost: 2000,
    category: "sofa",
    colors: ["gold", "silver"],
    size: ["L"],
    tags: ["luxury", "plush"],
    rating: 4.9,
    description: "A sofa that defines luxury.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 6,
    name: "Elegant Armchair",
    cost: 550,
    category: "chair",
    colors: ["beige", "brown"],
    size: ["M"],
    tags: ["elegant", "comfortable"],
    rating: 4.6,
    description: "An armchair designed for both comfort and elegance.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 7,
    name: "Round Coffee Table",
    cost: 250,
    category: "table",
    colors: ["black", "white", "brown"],
    size: ["S", "M"],
    tags: ["round", "modern"],
    rating: 4.3,
    description: "A modern round table perfect for coffee and conversations.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 8,
    name: "King-Size Bed",
    cost: 1800,
    category: "bed",
    colors: ["dark blue", "white"],
    size: ["L"],
    tags: ["king-size", "spacious"],
    rating: 5,
    description: "Sleep like royalty in this spacious king-size bed.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 9,
    name: "Minimalist Sofa",
    cost: 1300,
    category: "sofa",
    colors: ["grey", "white"],
    size: ["M", "L"],
    tags: ["minimalist", "sleek"],
    rating: 4.4,
    description: "A sleek and minimalist sofa for modern homes.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 10,
    name: "Bar Stool",
    cost: 120,
    category: "chair",
    colors: ["red", "black"],
    size: ["S"],
    tags: ["bar", "tall"],
    rating: 4.1,
    description: "A tall stool perfect for bar counters.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 11,
    name: "Retro Loveseat",
    cost: 850,
    category: "sofa",
    colors: ["mustard", "turquoise"],
    size: ["M"],
    tags: ["retro", "compact"],
    rating: 4.5,
    description: "A compact loveseat with a touch of the retro era.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 12,
    name: "Ceramic Side Table",
    cost: 280,
    category: "table",
    colors: ["cerulean", "white"],
    size: ["S"],
    tags: ["ceramic", "glossy"],
    rating: 4.2,
    description: "A glossy ceramic side table to elevate your room decor.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 13,
    name: "Canopy Bed",
    cost: 2000,
    category: "bed",
    colors: ["forest green", "beige"],
    size: ["L"],
    tags: ["canopy", "elegant"],
    rating: 4.9,
    description: "Elevate your bedroom with this elegant canopy bed.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 14,
    name: "Adjustable Desk Chair",
    cost: 400,
    category: "chair",
    colors: ["black", "silver"],
    size: ["M"],
    tags: ["adjustable", "ergonomic"],
    rating: 4.8,
    description: "Stay comfortable with this ergonomic adjustable desk chair.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 15,
    name: "Glass Dining Table",
    cost: 1200,
    category: "table",
    colors: ["glass", "silver"],
    size: ["L"],
    tags: ["modern", "glass"],
    rating: 4.7,
    description:
      "A modern glass dining table for sophisticated dining experiences.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 16,
    name: "Leather Recliner",
    cost: 1100,
    category: "chair",
    colors: ["dark brown", "black"],
    size: ["L"],
    tags: ["recliner", "leather", "comfort"],
    rating: 4.8,
    description: "A plush leather recliner designed for ultimate relaxation.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 17,
    name: "Nesting End Tables",
    cost: 500,
    category: "table",
    colors: ["natural wood", "white"],
    size: ["S", "M"],
    tags: ["nesting", "wood", "space-saving"],
    rating: 4.6,
    description: "Set of 2 nesting end tables, perfect for compact spaces.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 18,
    name: "Four-poster Bed",
    cost: 2100,
    category: "bed",
    colors: ["mahogany", "birch"],
    size: ["L"],
    tags: ["four-poster", "majestic", "wood"],
    rating: 5,
    description: "A majestic four-poster bed made of high-quality wood.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 19,
    name: "Convertible Futon",
    cost: 700,
    category: "sofa",
    colors: ["grey", "navy blue"],
    size: ["M", "L"],
    tags: ["futon", "convertible", "guests"],
    rating: 4.4,
    description:
      "A convertible futon, perfect for guests and small apartments.",
    picture: "https://via.placeholder.com/500",
  },
  {
    id: 20,
    name: "Swivel Bar Stool",
    cost: 140,
    category: "chair",
    colors: ["red", "black", "silver"],
    size: ["S"],
    tags: ["bar", "swivel", "metal"],
    rating: 4.2,
    description:
      "A metal swivel stool with a modern twist for bars and counters.",
    picture: "https://via.placeholder.com/500",
  },
];
